name: parse_server_sdk
description: Flutter plugin for Parse Server, (https://parseplatform.org), (https://back4app.com)
version: 1.0.16
homepage: https://github.com/phillwiggins/flutter_parse_sdk
author: PhillWiggins <phill.wiggins@gmail.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # Networking
  web_socket_channel: ^1.0.9
  http: ^0.12.0

  # Utils
  shared_preferences: ^0.5.0
  path_provider: ^0.4.1
  uuid: ^1.0.3
  package_info: ^0.4.0
  devicelocale: ^0.1.1

dev_dependencies:
  # Testing
  test: ^1.5.1
  flutter_test:
    sdk: flutter