name: parse_server_sdk
description: Flutter plugin for Parse Server, (https://parseplatform.org), (https://back4app.com)
version: 1.0.27
homepage: https://github.com/phillwiggins/flutter_parse_sdk

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.12.2
  flutter:
    sdk: flutter

  # Networking
  web_socket_channel: ^1.1.0
  connectivity: ^0.4.9+2

  #Database
  sembast: ^2.4.7+6
  xxtea: ^2.0.3
  shared_preferences: ^0.5.10

  # Utils
  path_provider: ^1.6.14
  uuid: ^2.2.2
  package_info: ^0.4.3
  devicelocale: ^0.3.1
  meta: ^1.1.8
  path: ^1.7.0

dev_dependencies:
  # Testing
  test: ^1.15.3
  mockito: ^4.1.1
