name: parse_server_sdk
description: Flutter plugin for Parse Server, (https://parseplatform.org), (https://back4app.com)
version: 1.0.23
homepage: https://github.com/phillwiggins/flutter_parse_sdk
author: PhillWiggins <phill.wiggins@gmail.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # Networking
  web_socket_channel: ^1.0.9
  http: ^0.12.0

  #Database
  sembast: ^1.15.1
  xxtea: ^2.0.2
  shared_preferences: ^0.5.2


  # Utils
  path_provider: ^0.5.0+1
  uuid: ^2.0.0
  package_info: ^0.4.0
  devicelocale: ^0.1.1

dev_dependencies:
  # Testing
  test: ^1.5.1
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter
