name: parse_server_sdk
description: Flutter plugin for Parse Server, (https://parseplatform.org), (https://back4app.com)
version: 1.0.28
homepage: https://github.com/phillwiggins/flutter_parse_sdk

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.12.2
  flutter:
    sdk: flutter

  # Networking
  web_socket_channel: ^1.1.0
  connectivity: ^0.4.9+2 # only used in the flutter part

  #Database
  sembast: ^2.4.7+6
  xxtea: ^2.0.3
  shared_preferences: ^0.5.10 # TODO(maaeps): 'remove' from dart part

  # Utils
  path_provider: ^1.6.14 # TODO(maaeps): 'remove' from dart part
  uuid: ^2.2.2
  package_info: ^0.4.3 # only used in the flutter part
  meta: ^1.1.8
  path: ^1.7.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
