name: parse_server_sdk
description: Dart plugin for Parse Server, (https://parseplatform.org), (https://back4app.com)
version: 3.0.0
homepage: https://github.com/phillwiggins/flutter_parse_sdk

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  # Networking
  dio: ^4.0.0
  http: ^0.13.1
  web_socket_channel: ^2.0.0

  #Database
  sembast: ^3.0.1
  sembast_web: ^2.0.0+2
  xxtea: ^2.1.0

  # Utils
  uuid: ^3.0.4
  meta: ^1.3.0
  path: ^1.8.0
  mime_type: ^1.0.0

dev_dependencies:
  # Testing
  build_runner: ^2.0.1
  mockito: ^5.0.4
  test: ^1.16.8
