name: parse_server_sdk
description: Dart plugin for Parse Server, (https://parseplatform.org), (https://back4app.com)
version: 2.1.0
homepage: https://github.com/phillwiggins/flutter_parse_sdk

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:

  # Networking
  dio: ^3.0.10
  http: ^0.12.2
  web_socket_channel: ^1.2.0

  #Database
  sembast: ^2.4.9
  sembast_web: ^1.2.0+1
  xxtea: ^2.0.3

  # Utils
  uuid: ^2.2.2
  meta: ^1.2.4
  path: ^1.7.0
  mime_type: ^0.3.2

dev_dependencies:
  # Testing
  test: ^1.15.7
  mockito: ^4.1.3
