name: parse_server_sdk
description: Dart plugin for Parse Server, (https://parseplatform.org), (https://back4app.com)
version: 2.0.1
homepage: https://github.com/phillwiggins/flutter_parse_sdk

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:

  # Networking
  dio: ^3.0.10
  web_socket_channel: ^1.1.0

  #Database
  sembast: ^2.4.7+6
  sembast_web: ^1.2.0
  xxtea: ^2.0.3

  # Utils
  uuid: ^2.2.2
  meta: ^1.1.8
  path: ^1.7.0
  mime_type: ^0.3.2

dev_dependencies:
  # Testing
  test: ^1.15.3
  mockito: ^4.1.1
