name: flutter_plugin_example
description: Demonstrates how to use the parse_server_sdk_flutter plugin.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=3.3.10"

dependencies:
  flutter:
    sdk: flutter

  parse_offline_extension: ^1.0.0
  parse_server_sdk: 9.0.0

  cupertino_icons: ^1.0.5
  path: ^1.8.2
  path_provider: ^2.0.15
  sembast: ^3.4.6+1
  shared_preferences: ^2.2.0

# Uncomment for local testing
# dependency_overrides:
#   parse_server_sdk:
#     path: ../../dart

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/parse.png
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
