name: parse_server_sdk_flutter
description: The Flutter SDK to connect to Parse Server. Build your apps faster with Parse Platform, the complete application stack.
version: 9.0.0-offline
homepage: https://parseplatform.org
repository: https://github.com/parse-community/Parse-SDK-Flutter
issue_tracker: https://github.com/parse-community/Parse-SDK-Flutter/issues
documentation: https://docs.parseplatform.org/flutter/guide

funding:
  - https://opencollective.com/parse-server
  - https://github.com/sponsors/parse-community

topics:
  - parse
  - parse-platform
  - parse-server
  - node-js
  - backend

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter

  parse_server_sdk:
    git:
      url: https://github.com/massimilianogalanti/Parse-SDK-Flutter.git
      path: packages/dart
      ref: offline
  #parse_server_sdk: ^6.4.0
  # Uncomment for local testing
  #parse_server_sdk:
  #   path: ../dart

  # Networking
  connectivity_plus: ^6.0.3

  #Database
  shared_preferences: ^2.2.3
  sembast: ^3.6.0
  sembast_web: ^2.2.0

  # Utils
  path_provider: ^2.1.4
  package_info_plus: ^5.0.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8

screenshots:
  - description: Parse Platform logo.
    path: screenshots/logo.png
