name: parse_server_sdk_flutter
description: Flutter plugin for Parse Server, (https://parseplatform.org), (https://back4app.com)
version: 4.0.0
homepage: https://github.com/parse-community/Parse-SDK-Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  parse_server_sdk: ^4.0.0
  # Uncomment for local testing
  #parse_server_sdk:
  #   path: ../dart

  # Networking
  dio: ^5.0.1
  connectivity_plus: ^2.3.2 # only used in the flutter part

  #Database
  shared_preferences: ^2.0.15 # only used in the flutter part

  # Utils
  path_provider: ^2.0.10 # only used in the flutter part
  package_info_plus: ^1.4.2 # only used in the flutter part
  sembast: ^3.4.0+6
  sembast_web: ^2.1.0+4
  path: ^1.8.2 # required for transitive use only

dev_dependencies:
  flutter_lints: ^1.0.4
  # Testing
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  path_provider_platform_interface: ^2.0.6
  plugin_platform_interface: ^2.1.4
