name: parse_server_sdk_flutter
description: The Flutter SDK for Parse Platform (https://parseplatform.org)
version: 5.0.0
homepage: https://github.com/parse-community/Parse-SDK-Flutter

environment:
  sdk: ">=2.18.0 <3.1.0"

dependencies:
  flutter:
    sdk: flutter

  parse_server_sdk: ^5.0.0
  # Uncomment for local testing
  #parse_server_sdk:
  #   path: ../dart

  # Networking
  dio: ^5.0.1
  connectivity_plus: ^3.0.3 # only used in the flutter part

  #Database
  shared_preferences: ^2.0.18 # only used in the flutter part

  # Utils
  path_provider: ^2.0.13 # only used in the flutter part
  package_info_plus: ^3.0.3 # only used in the flutter part
  sembast: ^3.4.0+6
  sembast_web: ^2.1.0+4
  path: ^1.8.2 # required for transitive use only

dev_dependencies:
  flutter_lints: ^2.0.1
  # Testing
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  path_provider_platform_interface: ^2.0.6
  plugin_platform_interface: ^2.1.4
